### ISSUE TITLE
decryptAzure / encryptAzure  example

### ISSUE THREAD

**Issue by asc-adean** [VirtusLab/render#14]
Could this be added to the template example?  

Thanks

**Comment by antoniaklja** [comment]
@asc-adean PR has been raised, thanks for pointing this out!
more details regarding encryption process can be found here https://github.com/VirtusLab/crypt/blob/master/docs/getting-started-azure.md

**Comment by antoniaklja** [comment]
closing, examples are available [here](https://github.com/VirtusLab/render/tree/master/examples).
