### ISSUE TITLE
can't install via go

### ISSUE THREAD

**Issue by syne-** [VirtusLab/render#15]
I've tried to install render via go and it is giving me this error:
```
$ go get github.com/VirtusLab/render
# github.com/VirtusLab/render/renderer
../../../../go/src/github.com/VirtusLab/render/renderer/render.go:108:27: undefined: crypto.TemplateFunctions
```

**Comment by pawelprazak** [comment]
please use the binarny releases, go get will try to compile master branch

śr., 10 lip 2019, 13:16 użytkownik syne- <notifications@github.com> napisał:
