### ISSUE TITLE
is it possible to add a function via an external configuration file?

### ISSUE THREAD

**Issue by panovst** [VirtusLab/render#22]
Hello all!

spring library only supports int64 multiplication and division operations.

1. if I need operations with float I need to add a new function? 
2. this is only possible by making changes to the repository code? 
3. is it possible to add a function via an external configuration file?

**Comment by panovst** [comment]
@pawelprazak thanks for the answer!
I didn't write on go, but I will try to add a couple of functions )

**Comment by panovst** [comment]
@pawelprazak 
I added two functions locally in a separate branch. 
how do you work with PR? do you grant rights to push?

**Comment by pawelprazak** [comment]
you need to fork the repo and then create a PR from the fork to the upstream

here's an example of that workflow:
https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/
