### ISSUE TITLE
render as a kubectl plugin

### ISSUE THREAD

**Issue by antoniaklja** [VirtusLab/render#3]
Maybe we can consider the render as a kubectl plugin with:
- rendering and applying as an atomic operation (similar to helm upgrade)
- showing the difference (delta) with optional approval

example:
`kubectl render-apply -f [file|dir] -c [config]`

[Kubectl Diff #491](https://github.com/kubernetes/enhancements/issues/491)
[Kubediff: a tool for Kubernetes to show differences between running state and version controlled configuration.](https://github.com/weaveworks/kubediff)
[Extend kubectl with plugins](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/)

**Comment by pawelprazak** [comment]
could be tricky, but sounds fun :)
