### ISSUE TITLE
Add `cidrHostEnd` custom function

### ISSUE THREAD

**Issue by aescaler-a0d** [VirtusLab/render#37]
Perhaps I'm just bad at using things (very plausible), but one of my use cases for render has me needing the last addressable address in a subnet.
To make this more functional, I figured I could make the function behave similar to `cidrHost` except the first argument would start from the end of the addressable range and work backwards.

**Comment by bartoszj** [comment]
Hello. As I remember you are able to provide negative number. `-1` would return broadcast address of the network, `-2` should return the last IP address of the network.
