### ISSUE TITLE
go 1.11 unexpected module path "github.com/sirupsen/logrus"

### ISSUE THREAD

**Issue by reefbarman** [VirtusLab/render#4]
It seems that in your repo you are referring to github.com/Sirupsen/logrus but go 1.11 and its modules are case sensitive and the actual path is github.com/sirupsen/logrus notice the lowercase s on sirupsen

This is currently meaning I can't include your module when using go 1.11

**Comment by pawelprazak** [comment]
thank you for pointing this out, https://github.com/VirtusLab/render/commit/56a3a66abd13aa93a1d3d43da4930707ede6c60a should fix this

**Comment by pawelprazak** [comment]
Also the just released https://github.com/VirtusLab/render/releases/tag/v0.0.5 has this commit
