### ISSUE TITLE
Using --set/--var value with spaces causes error

### ISSUE THREAD

**Issue by tw-pmcfadden** [VirtusLab/render#7]
test.tmpl
```
{{ .my_var }}
```
render --in test.tmpl --out test.out --set "my_var=something with spaces"

**Expected output:**
`cat test.out` > `something with spaces`

**Actual output:**
```
ERRO Expected a valid extra parameter: 'my_var=something with spaces'
ERROR: can't parse extra configuration variables: invalid parameter: 'my_var=something with spaces'
```

I know the regex match `^(?P<name>\S+)=(?P<value>\S*)$` is looking for non-whitespace. maybe we allow quotes around the value? Sorry, I'm not super knowledgable about golang to know what's appropriate.
Current workaround is to use a config file instead

**Comment by pawelprazak** [comment]
I've reproduced the issue in thests and implemented a fix, hope it helps

Released in https://github.com/VirtusLab/render/releases/tag/v0.0.7
